# Generated by Django 4.2.2 on 2024-02-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lashes", "0002_rename_yourmodelname_lashes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lashes",
            name="length",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lashes",
            name="width",
            field=models.CharField(max_length=20),
        ),
    ]
