# Generated by Django 4.2.2 on 2024-02-06 20:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("glue", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnotherModel",
            new_name="Glue",
        ),
    ]
