# Generated by Django 4.2.2 on 2024-02-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("glue", "0002_rename_anothermodel_glue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="glue",
            name="content",
            field=models.CharField(max_length=10),
        ),
    ]
